import turtle
import csv
def repositionTurtle(x, y, myTurtle):
       myTurtle.goto(x,y)
def writePoodleAttributes(linePoodle, myTurtle, window):
       myTurtle.penup()
       repositionTurtle(-420, 100, myTurtle)
       window.addshape("Poodle.gif")
       myTurtle.shape("Poodle.gif")
       myTurtle.stamp()
       myTurtle.shape('classic')
       myTurtle.right(90)
       myTurtle.forward(150)
       myTurtle.write(linePoodle[0], align="center")
       myTurtle.forward(25)
       myTurtle.write(linePoodle[1], align="center")
       myTurtle.forward(25)
       myTurtle.write(linePoodle[2], align="center")
       myTurtle.forward(25)
       myTurtle.write(linePoodle[3], align="center")
       repositionTurtle(-250, 100, myTurtle)
def writeRetrieverAttributes(lineRetriever, myTurtle, window):
       myTurtle.penup()
       window.addshape("Retriever.gif")
       myTurtle.shape("Retriever.gif")
       myTurtle.stamp()
       myTurtle.shape('classic')
       myTurtle.forward(100)
       myTurtle.write(lineRetriever[0], align="center")
       myTurtle.forward(25)
       myTurtle.write(lineRetriever[1], align="center")
       myTurtle.forward(25)
       myTurtle.write(lineRetriever[2], align="center")
       myTurtle.forward(25)
       myTurtle.write(lineRetriever[3], align="center")
       repositionTurtle(-85, 100, myTurtle)
def writeHuskyAttributes(lineHusky, myTurtle, window):
       myTurtle.penup()
       window.addshape("Husky.gif")
       myTurtle.shape("Husky.gif")
       myTurtle.stamp()
       myTurtle.shape('classic')
       myTurtle.forward(65)
       myTurtle.write(lineHusky[0], align="center")
       myTurtle.forward(25)
       myTurtle.write(lineHusky[1], align="center")
       myTurtle.forward(25)
       myTurtle.write(lineHusky[2], align="center")
       myTurtle.forward(25)
       myTurtle.write(lineHusky[3], align="center")
       repositionTurtle(70, 100, myTurtle)
def writeChihuahuaAttributes(lineChihuahua, myTurtle, window):
       myTurtle.penup()
       window.addshape("Chihuahua.gif")
       myTurtle.shape("Chihuahua.gif")
       myTurtle.stamp()
       myTurtle.shape('classic')
       myTurtle.forward(65)
       myTurtle.write(lineChihuahua[0], align="center")
       myTurtle.forward(25)
       myTurtle.write(lineChihuahua[1], align="center")
       myTurtle.forward(25)
       myTurtle.write(lineChihuahua[2], align="center")
       myTurtle.forward(25)
       myTurtle.write(lineChihuahua[3], align="center")
       repositionTurtle(210, 100, myTurtle) 
def writeBulldogAttributes(lineBulldog, myTurtle, window):
       myTurtle.penup()
       window.addshape("Bulldog.gif")
       myTurtle.shape("Bulldog.gif")
       myTurtle.stamp()
       myTurtle.shape('classic')
       myTurtle.forward(65)
       myTurtle.write(lineBulldog[0], align="center")
       myTurtle.forward(25)
       myTurtle.write(lineBulldog[1], align="center")
       myTurtle.forward(25)
       myTurtle.write(lineBulldog[2], align="center")
       myTurtle.forward(25)
       myTurtle.write(lineBulldog[3], align="center")
       myTurtle.hideturtle()
def main():
    bob = turtle.Turtle()
    wn = turtle.Screen()
    file = open("dogBreeds.csv", "r")
    csv_reader = csv.reader(file)
    lineList = []
    for row in csv_reader:
        lineList.append(row)
    writePoodleAttributes(lineList[0], bob, wn)
    writeRetrieverAttributes(lineList[1], bob, wn)
    writeHuskyAttributes(lineList[2], bob, wn)
    writeChihuahuaAttributes(lineList[3], bob, wn)
    writeBulldogAttributes(lineList[4], bob, wn)
    wn.exitonclick()  # last statement
main()
