import turtle #Grabbing the turtle module

canvas = turtle.Screen() #creates a canvas to draw upon

alex = turtle.Turtle() #create a turtle named Alex
alex.shape("turtle")
def drawBase():
    alex.fillcolor("red") 
    alex.begin_fill()
    alex.forward(200)
    alex.right(90)
    alex.forward(200)
    alex.right(90) 
    alex.forward(200)
    alex.right(90)
    alex.forward(200) 
    alex.end_fill()
def drawRoof():
    alex.fillcolor("blue")   
    alex.begin_fill()
    alex.right(90)
    alex.forward(200)
    alex.left(120)
    alex.forward(200)
    alex.left(120) 
    alex.forward(200)
    alex.end_fill()
def drawWindows():
    alex.fillcolor("orange")
    alex.left(30)
    alex.forward(200)
    alex.left(90)
    alex.forward(90)
    alex.left(90)
    alex.penup() 
    alex.forward(140)
    alex.begin_fill() 
    alex.left(90) 
    alex.pendown()
    alex.end_fill()  
    alex.begin_fill() 
    alex.forward(50)
    alex.left(90)
    alex.forward(50)
    alex.left(90)
    alex.forward(50)
    alex.left(90)
    alex.forward(50) 
    alex.right(90)
    alex.penup()
    alex.forward(70)
    alex.pendown()    
    alex.right(90)
    alex.forward(50)
    alex.right(90)
    alex.forward(50)
    alex.right(90)
    alex.forward(50)
    alex.right(90)
    alex.forward(50)
    alex.end_fill()
#def drawDoor(): 
        
def main(): 
    drawBase()
    drawRoof()
    drawWindows()
main() 
canvas.exitonclick() #You want this to be the last line, so keep pushing it down
